// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/mateuszkrasucki/go/src/github.com/mateuszkrasucki/calculator/pkg/reversepolish/postfixparser.go

// Package reversepolish is a generated GoMock package.
package reversepolish

import (
	gomock "github.com/golang/mock/gomock"
	lexer "github.com/mateuszkrasucki/calculator/pkg/lexer"
	reflect "reflect"
)

// MockNumericItem is a mock of NumericItem interface
type MockNumericItem struct {
	ctrl     *gomock.Controller
	recorder *MockNumericItemMockRecorder
}

// MockNumericItemMockRecorder is the mock recorder for MockNumericItem
type MockNumericItemMockRecorder struct {
	mock *MockNumericItem
}

// NewMockNumericItem creates a new mock instance
func NewMockNumericItem(ctrl *gomock.Controller) *MockNumericItem {
	mock := &MockNumericItem{ctrl: ctrl}
	mock.recorder = &MockNumericItemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNumericItem) EXPECT() *MockNumericItemMockRecorder {
	return m.recorder
}

// GetType mocks base method
func (m *MockNumericItem) GetType() lexer.ItemType {
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(lexer.ItemType)
	return ret0
}

// GetType indicates an expected call of GetType
func (mr *MockNumericItemMockRecorder) GetType() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockNumericItem)(nil).GetType))
}

// GetString mocks base method
func (m *MockNumericItem) GetString() string {
	ret := m.ctrl.Call(m, "GetString")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetString indicates an expected call of GetString
func (mr *MockNumericItemMockRecorder) GetString() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetString", reflect.TypeOf((*MockNumericItem)(nil).GetString))
}

// GetValue mocks base method
func (m *MockNumericItem) GetValue() float64 {
	ret := m.ctrl.Call(m, "GetValue")
	ret0, _ := ret[0].(float64)
	return ret0
}

// GetValue indicates an expected call of GetValue
func (mr *MockNumericItemMockRecorder) GetValue() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValue", reflect.TypeOf((*MockNumericItem)(nil).GetValue))
}
